"""
First-class audit record for every proposed cluster action — approved,
blocked, or executed. This is the first backend model with genuinely
backend-only fields (requested_by, policy metadata) that have no reason to
exist in the cross-service shared/schemas contract — see docs/ARCHITECTURE.md
'core/ vs shared/ boundary' and the Day 2 guide's note anticipating this.
"""

from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field


class ActionAudit(BaseModel):
    id: str  # UUID, generated by the service layer — see remediation_service.py
    action: str
    node: str
    requested_by: str = "operator"
    dry_run: bool
    policy_decision: str
    policy_risk_level: str
    policy_reason: str
    executed: bool = False
    result: dict[str, Any] | None = None
    error: str | None = None
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
    )
