apiVersion: v1
kind: ServiceAccount
metadata:
  name: kronvel-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kronvel-agent-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kronvel-agent-binding
subjects:
  - kind: ServiceAccount
    name: kronvel-agent
    namespace: default
roleRef:
  kind: ClusterRole
  name: kronvel-agent-role
  apiGroup: rbac.authorization.k8s.io